conversions = {
    "C"                 : "c",
    "온라인서비스"      : "c",
    "상주배치"          : "batch",
    "배치"              : "batch",
    "배치(*.pc)"        : "batch",
    "프로프레임"        : "proframe",
    "xml"               : "xml",
    "XML"               : "xml",
    "Web"               : "web",
    "웹_비지니스(.xml)" : "web",
    "웹_서식(.xml)"     : "web",
    "DBIO"              : "dbio",
    "DBIO MAP"          : "dbio",
    "Shell"             : "linux",
    "SHELL"             : "linux",
    "HEADER"            : "header",
    "Header FILE"       : "header",
    "MODULE"            : "module",
    "공통모듈"          : "module",
    "IO포맷 ALL"        : "IO",
    "IO포맷"            : "IO",
    "iDev@Tool"         : "iDev",
    "iDev@BuildLink"    : "iDev",
    "채널매핑룰"        : "iDev",
    "채널화면_mrd"      : "iDev",
    "채널화면_txt"      : "iDev",
    "채널화면_MAP"      : "iDev",
    "거래코드"          : "code",
    "연동코드"          : "code",
}